<?php
session_start();
require 'db.php';
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'student') { header('Location: index.php'); exit(); }
function e($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
$student_id = (int)($_SESSION['user_id'] ?? 0);
$conn->query("CREATE TABLE IF NOT EXISTS student_subjects (id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, schedule_id INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY unique_enrollment (student_id, schedule_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$stmt = $conn->prepare("SELECT s.subject, s.course, s.section, s.schedule_date, s.start_time, s.end_time, s.room, s.faculty FROM student_subjects ss JOIN schedules s ON s.id=ss.schedule_id WHERE ss.student_id=? ORDER BY s.schedule_date,s.start_time,s.subject");
$stmt->bind_param('i', $student_id); $stmt->execute(); $rows = $stmt->get_result();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enrolled Subjects - SAMS</title><link rel="stylesheet" href="student.css?v=7"><link rel="stylesheet" href="student-enhancements.css?v=1"></head><body><div class="header"><div class="header-title"><h2>ACLC College of Malolos - SAMS</h2><span>Complete enrolled-subject table</span></div><div class="header-user"><a href="student.php">Dashboard</a><a href="logout.php">Logout</a></div></div><main class="container"><h1>My Enrolled Subjects</h1><p class="subtitle">Schedules assigned to your student account.</p><div class="table-wrap"><table><thead><tr><th>Subject</th><th>Course / Section</th><th>Date</th><th>Time</th><th>Room</th><th>Faculty</th></tr></thead><tbody><?php if ($rows->num_rows === 0): ?><tr><td colspan="6" class="empty-state">No enrolled subjects found.</td></tr><?php else: while ($row=$rows->fetch_assoc()): ?><tr><td><strong><?php echo e($row['subject']); ?></strong></td><td><?php echo e($row['course'].' '.$row['section']); ?></td><td><?php echo e($row['schedule_date']); ?></td><td><?php echo e(substr($row['start_time'],0,5).' - '.substr($row['end_time'],0,5)); ?></td><td><?php echo e($row['room'] ?: '—'); ?></td><td><?php echo e($row['faculty'] ?: '—'); ?></td></tr><?php endwhile; endif; ?></tbody></table></div></main></body></html>
